import { ArrowDownRight, ArrowRight, GitBranch, GitMerge, PenLine, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router'

export default function Home() {
  return <>
    <section className="hero container"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-line" /> A new way to make stories together</span><h1 tabIndex={-1}>Two voices.<br /><em>One living world.</em></h1><p className="hero-lede">Write different scenes for the same story. Independent GenLayer validators decide whether they belong in one shared canon or need their own paths.</p><div className="hero-actions"><Link className="button button-primary" to="/worlds/new">Start a world <ArrowRight size={18} aria-hidden="true" /></Link><Link className="text-link" to="/worlds">Explore worlds <ArrowDownRight size={18} aria-hidden="true" /></Link></div><p className="hero-note">A funded round uses 2 GEN. Your scenes are public and wallet-signed.</p></div><div className="hero-art" aria-hidden="true"><div className="art-orbit art-orbit-one" /><div className="art-orbit art-orbit-two" /><div className="art-card art-card-a"><span>CHAPTER 01 / VOICE A</span><strong>The crow sings.</strong><p>The cheese slips from her beak as the fox waits below.</p></div><div className="art-card art-card-b"><span>CHAPTER 01 / VOICE B</span><strong>The fox catches it.</strong><p>A falling piece finds a new owner before it reaches the ground.</p></div><div className="art-merge"><GitMerge size={24} /><span>One story can hold both</span></div></div></section>
    <section className="value-band"><div className="container value-inner"><span className="eyebrow">THE CORE IDEA</span><p>A world grows by meaning, not by whoever controls a server. The merge decision changes the next chapter people can actually write.</p><Link to="/help" className="light-link">See how it works <ArrowRight size={18} aria-hidden="true" /></Link></div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">THE WRITING JOURNEY</span><h2>Let the story branch.<br /><em>Let it find its shape.</em></h2></div><p>Each round begins with a short canon, two invited writers, and a clearly stated 2 GEN collaboration purse.</p></div><div className="steps-grid"><div className="step-card"><span className="step-number">01</span><PenLine size={31} strokeWidth={1.5} aria-hidden="true" /><h3>Set the world</h3><p>The host defines the scene and its rules, chooses two writers, and funds a round.</p></div><div className="step-card"><span className="step-number">02</span><GitBranch size={31} strokeWidth={1.5} aria-hidden="true" /><h3>Write two paths</h3><p>Each invited writer submits a scene under the same parent. The exact words become public game commitments.</p></div><div className="step-card"><span className="step-number">03</span><ShieldCheck size={31} strokeWidth={1.5} aria-hidden="true" /><h3>See what belongs</h3><p>Validators check story consistency. A coherent pair shares one canon and splits 2 GEN; a conflict forms two forks and refunds the host.</p></div></div></section>
    <section className="section cta-section"><div className="container cta-inner"><div><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>A story is richer when more than one writer can shape it.</h2><p>See the worlds people have opened, or invite your own pair of voices.</p></div><div className="cta-actions"><Link className="button button-cream" to="/worlds/new">Start a world <ArrowRight size={18} aria-hidden="true" /></Link><Link className="text-link light-link" to="/worlds">Browse worlds</Link></div></div></section>
  </>
}
